baseURL = "https://lingo56.github.io/portfolio/"
languageCode = 'en-us'
title = 'Peter Soava'
theme = 'risotto'
canonifyURLs = true

[[module.mounts]]
  source = 'static'
  target = 'static'

[params]
  author = "Peter Soava"

[params.theme]
  palette = "windows-95"

[params.about]
  description = "![An image of Peter Soava's face](/images/profile.jpg) Fourth-year Undergraduate at Simon Fraser University"

[[params.socialLinks]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://github.com/Lingo56"

[[params.socialLinks]]
  icon = "fa-brands fa-itch-io"
  title = "Itch.io"
  url = "https://lingo56.itch.io/"

[[params.socialLinks]]
  icon = "fa-brands fa-linkedin"
  title = "LinkedIn"
  url = "https://www.linkedin.com/in/peter-soava/"

[[params.socialLinks]]
  icon = "fa-solid fa-envelope"
  title = "Email"
  url = "mailto:pgs2@sfu.ca"

[menu]

  [[menu.main]]
  identifier = "projects"
  name       = "All Projects"
  url        = "projects/"
  weight     = 1 

[taxonomies]
  tag = "tags"
  category = "categories"