baseURL = "https://lingo56.github.io/portfolio/"
languageCode = 'en-us'
title = 'Peter Soava'
theme = 'risotto'

[params]
  author = "Peter Soava"

[menu]

  [[menu.main]]
  identifier = "projects"
  name       = "Projects"
  url        = "/projects/"
  weight     = 1