baseURL = "https://lingo56.github.io/portfolio/"
languageCode = 'en-us'
title = 'Peter Soava'
theme = 'risotto'

[params]
  author = "Peter Soava"

[params.about]
  title = "risotto"
  description = "A [hugo](https://gohugo.io) theme inspired by terminal ricing."
  # or use an image:
  logo_image = "images/profile.jpg"

[menu]

  [[menu.main]]
  identifier = "projects"
  name       = "Projects"
  url        = "/projects/"
  weight     = 1 