baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Peter Soava'
theme = 'risotto'

[params]
  author = "Peter Soava"

[menu]

  [[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/blog/"
  weight     = 1

  [[menu.main]]
  identifier = "projects"
  name       = "Projects"
  url        = "/projects/"
  weight     = 2