baseURL = "http://localhost:1313/"
languageCode = 'en-us'
title = 'Peter Soava'
theme = 'risotto'

[params]
  author = "Peter Soava"
  productionBaseURL = "https://lingo56.github.io/"

[menu]

  [[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/blog/"
  weight     = 1

  [[menu.main]]
  identifier = "projects"
  name       = "Projects"
  url        = "/projects/"
  weight     = 2